language: php
php:
- 5.6
install: composer install --dev

travisdeployer:
  verbose: false
  branches:
    master: production
after_success:
- vendor/bin/travisdeployer
before_install:
- openssl aes-256-cbc -K $encrypted_2cc58f22e45b_key -iv $encrypted_2cc58f22e45b_iv -in deploy.php.enc -out deploy.php -d
